
#define IDH_TOPIC_PAGINA_PRINCIPAL                                                       3
#define IDH_TOPIC_PRESENTACION                                                           10
#define IDH_TOPIC_INTRODUCCION_A_SYS_MINING_                                             1
#define IDH_TOPIC_PRODUCTOS_BASE_SYS_MINING_                                             3443
#define IDH_TOPIC_A_QUIEN_ESTA_DIRIGIDO                                                  1558
#define IDH_TOPIC_FUNCIONAMIENTO                                                         1510
#define IDH_TOPIC_ENTORNO_PRINCIPAL_DEL_SYS_MINING__                                     2
#define IDH_TOPIC_MINERIA_DE_APLICACIONES                                                388
#define IDH_TOPIC_BASE_DE_CONOCIMIENTO__ARBOL_DE_COMPONENTES_                            341
#define IDH_TOPIC_MENU_CONTEXTUAL                                                        5
#define IDH_TOPIC_DIAGRAMA_DEL_SISTEMA                                                   2144
#define IDH_TOPIC_DIAGRAMA_DEL_SISTEMA_DEMO                                              2190
#define IDH_TOPIC_BARRA_DE_MENUS_DIAGRAMA_DEL_SISTEMA                                    1637
#define IDH_TOPIC_LISTA_DEPENDENCIA_DE_COMPONENTES                                       165
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_1                                 73
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_1                                     166
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_1                                     218
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_1                              274
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_1                             667
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_1                                       669
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_1                                 671
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_1                 673
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_1                     675
#define IDH_TOPIC_LISTA_DE_COMPONENTES_1                                                 18
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_2                                 96
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_2                                     167
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_2                                     219
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_2                              275
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_2                             434
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_2                                       528
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_2                                 622
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_2                 716
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_2                     810
#define IDH_TOPIC_DIAGRAMA_DE_ANALISIS_DE_IMPACTO                                        79
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_1                                    94
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_3                                 133
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_3                                     168
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_3                                     220
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_3                              276
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_3                             777
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_3                                       779
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_3                                 792
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_3                 841
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_3                     843
#define IDH_TOPIC_DIAGRAMA_DE_BLOQUES                                                    216
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBSRC_VR4C0055                                   175
#define IDH_TOPIC_DIAGRAMA_DE_FLUJO_INTERACTIVO                                          1100
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_4                                 186
#define IDH_TOPIC_DIAGRAMA_DE_FLUJO_COBOL                                                1127
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_                                  213
#define IDH_TOPIC_DIAGRAMA_JERARQUICO_DE_COBOL                                           1149
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_5                                 217
#define IDH_TOPIC_DIAGRAMA_DE_FLUJO_COPY                                                 1162
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_4                                     221
#define IDH_TOPIC_DIAGRAMA_DE_FLUJO                                                      1176
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_4                                       543
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_4                                 846
#define IDH_TOPIC_DIAGRAMA_DE_FLUJO_CON_COMENTARIOS                                      1172
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_DIAGRAMA_DE_FLUJO_CON_COMENTARIOS       542
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_DIAGRAMA_DE_FLUJO_CON_COMENTARIOS 848
#define IDH_TOPIC_DIAGRAMA_DE_COMPONENTES                                                1022
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_2                                    124
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_6                                 227
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_4                                     169
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_5                                     222
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_4                              277
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_4                             451
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_5                                       545
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_5                                 639
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_4                 733
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_4                     827
#define IDH_TOPIC_DOCUMENTACION_EXTERNA                                                  606
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_7                                 238
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_6                                       546
#define IDH_TOPIC_BARRA_DE_MENUS_DOCUMENTACION_EXTERNA                                   1713
#define IDH_TOPIC_DRILL_DOWN                                                             273
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_8                                 247
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_5                                     173
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_5                              281
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_5                             455
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_7                                       549
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_6                                 643
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_5                 737
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_5                     831
#define IDH_TOPIC_DRILL_UP                                                               418
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_3                                    135
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_9                                 301
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_6                                     174
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_6                                     228
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_6                              282
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_6                             456
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_8                                       550
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_7                                 644
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_6                 738
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_6                     832
#define IDH_TOPIC_REFERENCIAS_CRUZADAS                                                   700
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_4                                    139
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_10                                351
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_7                                     184
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_7                                     230
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_7                              284
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_7                             458
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_9                                       552
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_8                                 646
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_7                 740
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_7                     834
#define IDH_TOPIC_PROPIEDADES                                                            512
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_11                                313
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_8                                     183
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_8                                     229
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_8                              283
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_8                             457
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_10                                      551
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_9                                 645
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_8                 739
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_8                     833
#define IDH_TOPIC_VER_FUENTE                                                             794
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_5                                    490
#define IDH_TOPIC_PROGRAMA_COBOL___CBL_COBLIN_RSSBT000_12                                605
#define IDH_TOPIC_TRANSACCIONES___CCT_DEMOCCT_M001_9                                     185
#define IDH_TOPIC_COPY_COBOL___CPY_COBCPY_CGTL0020_9                                     231
#define IDH_TOPIC_TARJETAS_DE_DATOS___CTC_COBCTC_VRCDEP01_9                              285
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_9                             761
#define IDH_TOPIC_PROC_JCL___JCL_COBPRC_VRPCE001_11                                      764
#define IDH_TOPIC_DISPARADOR_JOB___JOB_COBJCL_VRJCE001_10                                766
#define IDH_TOPIC_SERVICIOS_DE_NEGOCIO___NEG_DEMONEG_MERCADO_DE_DINERO_9                 768
#define IDH_TOPIC_PROCESO_DE_NEGOCIO___NEP_DEMONEP_CARGA_DE_DINERO_9                     770
#define IDH_TOPIC_BARRA_DE_MENUS_VER_FUENTE                                              1729
#define IDH_TOPIC_VERSIONADO_DE_COMPONENTES                                              1180
#define IDH_TOPIC_VISTA_PREVIA                                                           1063
#define IDH_TOPIC_PANTALLA_IBM___BMS_COBBMS_RSSBM00_6                                    1024
#define IDH_TOPIC_DIAGRAMA_SCHEDULER                                                     1168
#define IDH_TOPIC_SCHEDULER_CTRL_M___CTR_COBCTR_CONTROLIBM_10                            698
#define IDH_TOPIC_BARRA_DE_MENUS_DIAGRAMAS                                               1730
#define IDH_TOPIC_BUSQUEDA_EN_COMPONENTES                                                1709
#define IDH_TOPIC_DESCRIPCION_DE_LA_VENTANA_BUSQUEDA_EN_COMPONENTES                      772
#define IDH_TOPIC_CONSULTA_DE_COMPONENTES                                                427
#define IDH_TOPIC_INVENTARIO_DE_COMPONENTES                                              578
#define IDH_TOPIC_LISTA_DE_COMPONENTES_2                                                 657
#define IDH_TOPIC_LISTA_DEPENDENCIAS_DE_COMPONENTES                                      883
#define IDH_TOPIC_MATRIZ_CRUD                                                            958
#define IDH_TOPIC_MATRIZ_ARCHIVOS_FISICOS                                                525
#define IDH_TOPIC_RECEPCION_DE_COMPONENTES                                               687
#define IDH_TOPIC_BARRA_DE_MENUS                                                         1000
#define IDH_TOPIC_DOCUMENTACION_DEL_SISTEMA_                                             663
#define IDH_TOPIC_PRODUCTOS_POR_TIPO                                                     813
#define IDH_TOPIC_BARRA_DE_MENUS_DOCUMENTACION_DEL_SISTEMA                               1700
#define IDH_TOPIC_CONVERSION_DE_COMPONENTES_                                             651
#define IDH_TOPIC_CONVERSION_                                                            816
#define IDH_TOPIC_SESION                                                                 377
#define IDH_TOPIC_ADMINISTRACION                                                         918
#define IDH_TOPIC_ACTUALIZAR                                                             1019
#define IDH_TOPIC_JERARQUIA_DE_CLASES                                                    1044
#define IDH_TOPIC_CLASES_POR_PRODUCTO                                                    1085
#define IDH_TOPIC_CREACION_DE_INDICES                                                    1113
#define IDH_TOPIC_MONITOREO_DE_USUARIOS                                                  2304
#define IDH_TOPIC_CAMBIO_DE_PASSWORD                                                     2336
#define IDH_TOPIC_CATALOGOS                                                              1197
#define IDH_TOPIC_BROWSE_EN_CATALOGOS                                                    1119
#define IDH_TOPIC_PARAMETROS                                                             1230
#define IDH_TOPIC_DESCRIPCION_TSPROG                                                     1868
#define IDH_TOPIC_ROLES                                                                  1173
#define IDH_TOPIC_USUARIOS                                                               1220
#define IDH_TOPIC_ASIGNA_ROL_A_USUARIO                                                   1278
#define IDH_TOPIC_CAPACIDADES                                                            1318
#define IDH_TOPIC_OFICINAS                                                               1357
#define IDH_TOPIC_SISTEMAS                                                               1403
#define IDH_TOPIC_CLASES                                                                 1472
#define IDH_TOPIC_BIBLIOTECAS                                                            1574
#define IDH_TOPIC_UTILERIAS                                                              1651
#define IDH_TOPIC_CARGA_DE_UTILERIAS                                                     1684
#define IDH_TOPIC_HERRAMIENTAS                                                           1715
#define IDH_TOPIC_ESTILO_DE_VENTANAS                                                     1745
#define IDH_TOPIC_REPORTEADOR                                                            1783
#define IDH_TOPIC_CONFIGURACION                                                          1799
#define IDH_TOPIC_REPORTES_                                                              1809
#define IDH_TOPIC_EDITOR_DE_DIAGRAMAS                                                    2393
#define IDH_TOPIC_BARRA_DE_MENUS_EDITOR_DE_DIAGRAMAS                                     2434
#define IDH_TOPIC_MENU_FILE                                                              2439
#define IDH_TOPIC_MENU_EDIT                                                              2448
#define IDH_TOPIC_MENU_VIEW                                                              2464
#define IDH_TOPIC_MENU_OBJECT                                                            2484
#define IDH_TOPIC_BARRA_DE_CAPAS                                                         2494
#define IDH_TOPIC_BARRA_DE_HERRAMIENTAS_ARCHIVO                                          1977
#define IDH_TOPIC_BARRA_DE_HERRAMIENTAS_LINEAS                                           2201
#define IDH_TOPIC_BARRA_DE_HERRAMIENTAS_DISENO                                           2004
#define IDH_TOPIC_BARRA_DE_HERRAMIENTAS_FUENTE                                           2059
#define IDH_TOPIC_BARRA_DE_HERRAMIENTAS_ALINEACION_                                      2087
#define IDH_TOPIC_VENTANAS_ACTIVAS                                                       505
#define IDH_TOPIC_AYUDA                                                                  1838
#define IDH_TOPIC_ENTORNO_DE_LA_VENTANA_DE_AYUDA                                         1761
#define IDH_TOPIC_ACERCA_DE_SYS_MINING_                                                  1840